### ISSUE TITLE
need more explanation...

### ISSUE THREAD

**Issue by ophott** [m3talstorm/foe-decryption#1]
Sorry i'm a newbie..

please explain these steps further..

This contains the 'decryption' algorithm, we want to 'extract' this and convert it to Python

The mostly likely things to change is the static ints in 'method_14' and/or the body in 'method_15'

The static array of (3) ints are renamed 'magic_bytes' and put at the top of 'decryption.py'

Make the Python class 'Decryption' in 'decryption.py' match the AS3 class inside of class_3

**Comment by m3talstorm** [comment]
HI @ophott what bit are you stuck on?

**Comment by ophott** [comment]
oh got it solved,,
