### ISSUE TITLE
what encryption is this?

### ISSUE THREAD

**Issue by veso266** [m3talstorm/foe-decryption#14]
Hi this is not specific to Forge of Empires but I realy don't know where to ask anymore
so I have a AS3 class: https://pastebin.com/a3hBERhZ which is encrypted somehow and I don't know what tool could create such a mess and of course how could I decrypt it

I think that this could be encrypted with this: http://www.amayeta.com/software/swfencrypt/#00 but I am not realy sure about that

Thanks for Anwsering and Best Regards

**Comment by diogofacin** [comment]
@veso266 , this is not encrypted, it's obfuscated.

There is no way to "deobfuscate" but some tools can help you analyzing/debugging the code a bit more easily.

Where did you get this piece of code?

**Comment by veso266** [comment]
I got it here: http://downloads.dxing.si/speedtest/speedtest-white.swf (realy old version of SpeedTest) I used ffdec to open it (and for some reason its deobfuscation tools didn't work this time) 

and after further analysis I found out that infact it is obfuscated with Amayeta SWF Encrypt (if you go to ActionScript Obfuscation: Encrypted Vs Non-Encrypted example you can see it produces same results as they advertise)

So now the question is how can I analyze and reverse this so I at least get partialy readable code 
because I think that 

```AS3
§\x01§ = 1360 + 658;
```
for instance probably have some meaning

there are also §§push(67305985); and §§pop() which I saw on other flash files as well (they probably mean something)

BTW: 
is 
```AS3
var _loc2_ = com["meychi"]["ascrypt"]["MD5"].calculate("something") 
```
same as 
```AS3
var _loc2_ = com.meychi.ascrypt.MD5.calculate("something")
```
