### ISSUE TITLE
v1.119

### ISSUE THREAD

**Issue by VividWombat** [m3talstorm/foe-decryption#15]
BUILD_NUMBER:String = "7cb313c7be";
      
BUILD_TIME:String = "05.02.2018 11:12";
      
VERSION_SECRET:String = "6q01Zd9YKTSEVjhtqqGEYjBGr3pUTRFojYL+m2/6GorQ892bVcY4QMoqLbc6A+DhXQEaMtZfkczMgiHt3tVJ4w==";
      
VERSION:String = "1.119";

**Comment by m3talstorm** [comment]
Thanks for the info @VividWombat, could you submit a PR please?

**Comment by VividWombat** [comment]
PR added
